### ISSUE TITLE
rfusefs gem is missing essential *.rb files

### ISSUE THREAD

**Issue by ManfredSauter** [lwoggardner/rfusefs#11]
The .gemspec for the rfusefs gem does not select all required library files. So the gem generated from this .gemspec fails due to missing files, even for the most basic examples, with errors like `cannot load such file -- fuse/fusedir (LoadError)`.

The gem appears to work properly after changing the selector for `s.files` from `'lib/**.rb'` to `'lib/**/*.rb'` in order to also include ruby files from all subdirectories.

**Comment by lwoggardner** [comment]
Oops. Will fix today.

**Comment by lwoggardner** [comment]
1.1.3 released
