### ISSUE TITLE
undefined method `backtrace' for nil:NilClass

### ISSUE THREAD

**Issue by leoc** [lwoggardner/rfusefs#2]
I implemented a simple fs managing kindle collection.

Got this error message a thousand times when trying to access the directory that lists all documents.

In my tests and specs everything works fine with a small amount of documents.

```
ERROR: Exception nil not an Errno:: !respond_to?(:errno) 
ERROR: Exception in exception!
ERROR: Exception #<NoMethodError: undefined method `backtrace' for nil:NilClass> not an Errno:: !respond_to?(:errno) 
/home/arthur/.rvm/gems/ruby-1.9.3-p125@kindlefs/gems/rfusefs-0.8.0/lib/rfusefs.rb:104:in `process'
/home/arthur/.rvm/gems/ruby-1.9.3-p125@kindlefs/gems/rfusefs-0.8.0/lib/rfusefs.rb:104:in `run'
bin/kindlefs:28:in `<main>'
```

Did you ever see one of those?

**Comment by PerpetuumMobile** [comment]
Hello, still encountering the issue.
Ruby 2.3.1, rfusefs 1.0.3

When I try to use File.read in read_file to return requested file, I get it content, but with the error
> ERROR: Exception nil not an Errno:: !respond_to?(:errno) 
ERROR: Exception in exception!
ERROR: Exception #<NoMethodError: undefined method `backtrace' for nil:NilClass> not an Errno:: !respond_to?(:errno) 
/home/mobil/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rfuse-1.1.2/lib/rfuse.rb:333:in `process'
/home/mobil/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rfuse-1.1.2/lib/rfuse.rb:333:in `loop'
/home/mobil/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rfuse-1.1.2/lib/rfuse.rb:293:in `run'
/home/mobil/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rfusefs-1.0.3/lib/fuse/rfusefs-fuse.rb:104:in `run'
/home/mobil/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rfuse-1.1.2/lib/rfuse.rb:244:in `main'
/home/mobil/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rfusefs-1.0.3/lib/rfusefs.rb:48:in `main'
/home/mobil/scripts/ruby/test/megafs/mega.rb:96:in \<main\>

Can I do some monkey patching to resolve it locally?

**Comment by mcarpenter** [comment]
I'm late to this party but maybe this will help some future traveller: the vanilla rfuse gem (to which rfusefs is related) throws the same error if, for example, the implementation of `#read` mistakenly returns more data than was requested by the caller. See the `size` parameter:

    read(ctx, path, size, offset, ffi)
